#!/bin/bash

mountbind(){
origin=/var/lib/docker/volumes/$1_data/_data/
target=/opt/dbdata-$NB_USER/$1/
if [ -d "$origin" ] && [ -d "$target" ]; then
        mount --bind $origin $target
fi
}
mountbind postgres
mountbind mysql
mountbind mongodb

exit 0

