#!/bin/bash

browser=$1

proxied_domain="hub.pluralcamp.com"

password=pluralcamp

chrome="google-chrome"
firefox="firefox"
brave="brave"

error_msg="ERROR: invalid browser. Valids browsers are $chrome, $firefox and $brave."

if [ ! -z "$browser" ]; then
	if [ "$browser" != "$chrome" ] && [ "$browser" != "chrome" ]; then
		if [ "$browser" != "$firefox" ]; then
			if [ "$browser" != "$brave" ]; then
				echo $error_msg
				exit 1
			fi
		fi
	fi
fi

#IP=$(echo $PROXY_PUBLIC_PORT | cut -d"/" -f3 | cut -d":" -f1)
IP=$INGRESS_PUBLIC_IP

if [ -z "$browser" ]; then
http_handler=$(gio mime x-scheme-handler/http)

if [ "$(echo $http_handler | grep $chrome)" != "" ]; then
	#echo "$chrome is installed"
	browser=$chrome
elif [ "$(echo $http_handler | grep $firefox)" != "" ]; then
	#echo "$firefox is installed"
	browser=$firefox
elif [ "$(echo $http_handler | grep $brave)" != "" ]; then
        #echo "$brave is installed"
	browser=$brave
fi
fi

record="$(grep $proxied_domain /etc/hosts)"

if [ ! -z "$record" ]; then
        sudo su root -c "grep -v \"$proxied_domain\" /etc/hosts > /tmp/hosts.tmp ; cp /tmp/hosts.tmp /etc/hosts"
fi

dns="$(grep $IP /etc/hosts)"

if [ -z "$dns" ]; then
	sudo su root -c "echo \"$IP $proxied_domain\" >> /etc/hosts"
fi

echo "Opening Entorn in $browser ..."

$browser https://$proxied_domain/hub/home --password-store=basic > /dev/null 2>&1 &

echo
echo "If required:"
echo "Username is $NB_USER"
echo "Password is $password"
echo
exit 0
