#!/bin/bash

dir=godrive

if [ -d "/home/$dir" ]; then
       sudo umount /home/$dir > /dev/null 2>&1
else
       sudo mkdir -p /home/$dir
       sudo chown $NB_USER:$NB_GID /home/$dir
fi

if [ ! -L "/home/$NB_USER/$dir" ]; then
   ln -s /home/$dir /home/$NB_USER/$dir
fi

if google-drive-ocamlfuse /home/$dir -browser google-chrome 2>/dev/null  ; then
   echo ;
   echo "Google Drive is now mounted at /home/$NB_USER/$dir" ;
   echo ;
else
   echo ;
   echo "Error: Mounting error. Check mounting point and authorization" ;
   echo ;
fi

exit 0
