#!/bin/bash

dir=godrive

if umount /home/$dir ; then
  echo
  echo "Google Drive is no longer mounted"
  echo
else
  echo
  echo "Error unmounting google drive. Maybe not mounted?"
  echo
fi

exit 0
