#!/bin/sh

process_name=$1

if [ ! -z "$process_name" ]; then
        pids=$(ps -aux | grep $process_name | tr -s ' ' | cut -f2 -d' ')
        kill -9 $pids
        echo "Processes with name $process_name have been killed"
else
        echo "You must supply a valid process name"
fi

