#!/bin/bash

ver="0.1.0"

#./build-entorn-io.sh dev
#./build-entorn-io.sh data
#./build-entorn-io.sh ops
#git checkout main
./build-entorn-io.sh full
#git checkout javaweb
#./build-entorn-io.sh javaweb

if [ "$1" == "all" ]; then
#docker tag entorn-io/singleuser-dev:$ver pluralcamp/entorn-io-dev:$ver
#docker tag entorn-io/singleuser-data:$ver pluralcamp/entorn-io-data:$ver
#docker tag entorn-io/singleuser-ops:$ver pluralcamp/entorn-io-ops:$ver
docker tag entorn-io/singleuser-full:$ver pluralcamp/entorn-io-full:$ver
#docker tag entorn-io/singleuser-javaweb:$ver pluralcamp/entorn-io-javaweb:$ver

docker_push(){
docker push $1
docker rmi $1
}

#docker_push pluralcamp/entorn-io-dev:$ver
#docker_push pluralcamp/entorn-io-data:$ver
#docker_push pluralcamp/entorn-io-ops:$ver
docker_push pluralcamp/entorn-io-full:$ver
#docker_push pluralcamp/entorn-io-javaweb:$ver

#docker rmi -f entorn-io/singleuser-dev:$ver
#docker rmi -f entorn-io/singleuser-data:$ver
#docker rmi -f entorn-io/singleuser-ops:$ver
#docker rmi -f entorn-io/singleuser-full:$ver
#docker rmi -f entorn-io/singleuser-javaweb:$ver
fi
######

echo "All built and pushed"

echo
exit 0
