#!/bin/bash
basename "$0"
f="$(basename -- $0)"

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    echo "Please supply the course name: $f <course_name>"
    exit 1
fi
ngshare-course-management create_course $1
exit 0
