#!/bin/bash
basename "$0"
f="$(basename -- $0)"

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    printf "Please supply the instructor username: \n $f <instructor_username> \nto remove it from the course $COURSE_NAME \n"
    printf "\nIf you want to remove an instructor from a different course: \n $f <instructor_username> <course_name>\n\n"
    exit 1
fi
instructor_id=$1
course_id=$COURSE_NAME
if [[ ! -z $2 ]]; then
	course_id=$2
fi

echo "Removing instructor with username $instructor_id from the course $course_id ..."

ngshare-course-management remove_instructor $course_id $instructor_id 
exit 0
