#!/bin/bash
basename "$0"
f="$(basename -- $0)"

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    printf "Please supply the student username: \n $f <student_username> \nto remove it from the course $COURSE_NAME \n"
    printf "\nIf you want to remove a student from a different course: \n $f <student_username> <course_name>\n\n"
    exit 1
fi
student_id=$1
course_id=$COURSE_NAME
if [[ ! -z $2 ]]; then
	course_id=$2
fi

echo "Removing student with username $student_id from the course $course_id ..."

ngshare-course-management remove_students $course_id $student_id 
exit 0
