#!/bin/bash
basename "$0"
f="$(basename -- $0)"

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    printf "Please supply the student username: \n $f <student_username> \nto add it to the course $COURSE_NAME \n"
    printf "\nIf you want to add the student to a different course: \n $f <student_username> <course_name>\n\n"
    exit 1
fi
student_id=$1
course_id=$COURSE_NAME
if [[ ! -z $2 ]]; then
	course_id=$2
fi

echo "Adding student with username $student_id to the course $course_id ..."

printf "Student's first name: "
first_name=`python -c "print(input())"`

printf "Student's  last name: "
last_name=`python -c "print(input())"`

printf "Student's email: "
email=`python -c "print(input())"`

ngshare-course-management add_student $course_id $student_id -f $first_name -l $last_name -e $email
exit 0
