#!/bin/bash
basename "$0"
f="$(basename -- $0)"

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    printf "Please supply the csv filename: \n $f <csv_filename> \nto add all students to the course $COURSE_NAME \n"
    printf "\nIf you want to add the students to a different course: \n $f <csv_filename> <course_name>\n\n"
    exit 1
fi
csv_filename=$1
course_id=$COURSE_NAME
if [[ ! -z $2 ]]; then
	course_id=$2
fi

echo "Adding / updating all students from $csv_filename to the course $course_id ..."

ngshare-course-management add_students $course_id $csv_filename 
exit 0
