version: '3.9'

services:
  idea:
    build:
      context: .
      args:
        IMAGE: "${IDEA_IMG:-jetbrains/projector-idea-c:2021.3-projector-v1.6.0}"
        NB_USER: "${NB_USER:-jovyan}"
        MONGO_VER: "${MONGO_VER:-5}"
    container_name: "idea_container_${IDEA_INAME:-projector-idea-c}"
    image: "idea_${IDEA_INAME:-projector-idea-c}"
    network_mode: 'host'
    environment:
        NB_USER: "${NB_USER:-jovyan}"
        DOCKER_HOST: "tcp://localhost:2375"
    volumes:
       - "home:/home/${NB_USER:-jovyan}"
       - docker:/var/lib/docker
       - /var/run/mysqld:/var/run/mysqld
       - /var/run/postgresql:/var/run/postgresql
    ports:
      - "${ideaport:-8887}:8887"

volumes:
  home:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${NB_USER}
  docker:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/docker


